[build]
  command = "next build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_EMAILJS_SERVICE_ID = "service_0k7sqys"
  NEXT_PUBLIC_EMAILJS_TEMPLATE_ID = "template_py1g735"
  NEXT_PUBLIC_EMAILJS_PUBLIC_KEY = "NcSUafJLSL3cqsMvt"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Configuration des redirections pour les SPA
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild" 