[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_EMAILJS_SERVICE_ID = "service_0k7sqys"
  NEXT_PUBLIC_EMAILJS_TEMPLATE_ID = "template_py1g735"
  NEXT_PUBLIC_EMAILJS_PUBLIC_KEY = "NcSUafJLSL3cqsMvt"

# Configuration pour les redirections et le support du routage Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuration des redirections pour les SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]}

[functions]
  node_bundler = "esbuild" 